### ISSUE TITLE
Plugin is not following `COMPOSER_HOME` if it's set

### ISSUE THREAD

**Issue by nesl247** [oh-my-fish/plugin-composer#8]
Composer has a `COMPOSER_HOME` variable which defines where the composer directory actually is. It's not always guaranteed to be `~/.composer`.

Also on Linux, you must use `XDG_CONFIG_HOME` if `COMPOSER_HOME` is not set, because composer now follows that spec.

**Comment by sagebind** [comment]
Using `XDG_CONFIG_HOME` is still not addressed. Perhaps check both `XDG_CONFIG_HOME` and `HOME` for backwards compatibility?

**Comment by bobthecow** [comment]
in other places, we've used a pattern like … `set -q XDG_CONFIG_HOME; or set -l XDG_CONFIG_HOME $HOME`, then referenced `$XDG_CONFIG_HOME` instead of `$HOME` where we need it.
